### ISSUE TITLE
[BUG] Returning incorrect ID

### ISSUE THREAD

**Issue by goldminer127** [mbdavid/LiteDB#1782]
**Version**
v5.0.8

**Describe the bug**
I am trying to store an object that has an id into the database. When I attempt to retrieve the object's id, it would return an incorrect form of the object's id. The id is a ulong.
**Code to Reproduce**
```
public class Player
    {
        public ulong ID { get; set; }
    }
public class Database
    {
        private LiteDatabase database;
        private ILiteCollection<Player> colPlayers;

        public string Path { get; set; }
        public List<Player> Players { get; private set; }

        public Database(string path)
        {
            Path = path;
            database = new LiteDatabase(Path);
            colPlayers = database.GetCollection<Player>("players");
            Players = colPlayers.FindAll().ToList();
        }
        public void AddPlayer(Player player, ulong id)
        {
            colPlayers.Insert(id, player);
            colPlayers.EnsureIndex(x => x.ID);
            Players = colPlayers.FindAll().ToList();
        }
        public Player GetPlayerByID(ulong id)
        {
            return colPlayers.FindById(id);
        }
    }
public class Program
    {
        public static Database Database { get; private set; }
        public static void Main(string[] args)
        {
            Console.WriteLine("Stored ID: 528233622268805130");
            Database = new Database("player.db");
            Database.AddPlayer(new Player() { ID = 528233622268805130 }, 528233622268805130);
            var ID = Database.GetPlayerByID(528233622268805130).ID;
            Console.WriteLine($"Returned Id: {ID}");
        }
    }
```
**Expected behavior**
Expected to return "Returned ID: 528233622268805130". Returned "Returned ID: 528233622268805120" instead.

**Screenshot**
![Screenshot (2)](https://user-images.githubusercontent.com/67210677/89680904-e9249d00-d8c1-11ea-9409-6c9f43f13695.png)
**Additional context**
Occurs with specific numbers. Also occurs with 302730148921344012, database returns 302730148921344000 instead.

**Comment by lbnascimento** [comment]
@goldminer127 LiteDB does not natively suport `UInt64`, but it supports `Int64` and `Double`. What is happening is that C# is implicitly casting the id to `Double` when you insert and when you retrieve it, and apparently `Double` is losing precision at such magnitudes (just try `Convert.ToDouble(528233622268805130).ToString("N0")` and you'll see it becomes 5282336222688051**2**0). Why C# is opting to implicitly cast it to `Double` instead of `Int64` is beyond me.

The easiest fix would be to simply change your id field to `Int64` (given that's how LiteDB will store your `UInt64` anyway). If that is not possible, you must be careful to always explicitly cast your `UInt64` to `Int64`, both when inserting and when retrieving.

A final tip: there's no need to pass both the entity and the id to ` colPlayers.Insert(...)`. The overload that takes both is meant to be used when you don't have the id field mapped in your class, which is not your case.

**Comment by goldminer127** [comment]
I see what you mean. C# casting the Id into a double instead of Int64 is strange to me too but that explains why the returned Id is incorrect with some numbers. I used the overload to add the Id because when I added [BsonId] I couldn't find the object with my  FindById method. When I used the overload it would be able to find the object with the correct BsonId but I assume that issue is due to the same reason with casting right?

**Comment by lbnascimento** [comment]
@goldminer127 I believe all of these problems are related to the implicit cast to double. Changing your property to `Int64` (or always casting it to `Int64` before usage) should solve these issues.

**Comment by goldminer127** [comment]
I casted everything to an Int64 and now I am getting the error
```
Unable to cast object of type 'System.Double' to type 'System.Int64'.
at lambda_method(Closure , Object , Object )
at LiteDB.BsonMapper.DeserializeObject(EntityMapper entity, Object obj, BsonDocument value)
at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
at LiteDB.LiteQueryable1.<ToEnumerable>b__27_2(BsonDocument x)
   at System.Linq.Enumerable.SelectEnumerableIterator2.ToList()
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at GameTime.Models.PlayerDatabase.get_Players() in C:\Users\Brand\source\repos\GameTime\GameTime\Models\PlayerDatabase.cs:line 18
at GameTime.Commands.PlayerCommands.UseItem(CommandContext ctx, String itemName) in C:\Users\Brand\source\repos\GameTime\GameTime\Commands\PlayerCommands.cs:line 221
at DSharpPlus.CommandsNext.Command.ExecuteAsync(CommandContext ctx)
```

**Comment by lbnascimento** [comment]
@goldminer127 Could you send me your updated code? Changing the `AddPlayer` and `GetPlayerByID` methods to take an `Int64` instead of `UInt64` worked for me. Keeping them as-is and casting the `UInt64` to `UInt64` before calling `colPlayers.Insert(...)` and `olPlayers.FindById(...)` also worked.

**Comment by nlogozzo** [comment]
Hi, @lbnascimento . I'm a friend of @goldminer127 trying to help him out.
The Player model class currently looks like:
```
public class Player
{
    [BsonID]
    public long ID { get; set; }
    //...
}
```
And the Add and Get methods are as follows:
```
public void AddPlayer(Player player)
{
    colPlayers.Insert(player);
    colPlayers.EnsureIndex(x => x.ID);
}

public Player GetPlayerByID(long id)
{
    return colPlayers.FindById(id);
}
```
When calling to one of these methods for example we use `var user = Bot.PlayerDatabase.GetPlayerByID(Convert.ToInt64(id));`
This is the updated code on what we are using and still getting the errors
